-- File: data_categories.sql
-- Purpose: Inserting values into the data_categories table
-- =========================================================

-- Inserting values into the data_categories table
INSERT INTO data_categories (data_category_name, data_category_description, data_category_schema, data_category_reference, data_category_recommended_databases) VALUES
('Real-Time Data', 'Data that is available immediately and updated continuously.', '{"type": "object", "properties": {"timestamp": {"type": "string", "format": "date-time"}, "value": {"type": "number"}}}', '{"example": "{"timestamp": "2024-01-01T00:00:00Z", "value": 123}"}', 'InfluxDB, Elasticsearch'),
('Historical Data', 'Data collected over time for analysis and trend observation.', '{"type": "object", "properties": {"date": {"type": "string", "format": "date"}, "value": {"type": "number"}}}', '{"example": "{"date": "2024-01-01", "value": 456}"}', 'PostgreSQL, MySQL'),
('Aggregated Data', 'Data compiled from multiple sources to provide a summary.', '{"type": "object", "properties": {"aggregate_type": {"type": "string"}, "total": {"type": "number"}}}', '{"example": "{"aggregate_type": "sum", "total": 789}"}', 'MongoDB, ClickHouse'),
('Categorical Data', 'Data divided into groups or categories.', '{"type": "object", "properties": {"category": {"type": "string"}, "count": {"type": "integer"}}}', '{"example": "{"category": "A", "count": 100}"}', 'Elasticsearch, MongoDB'),
('Text Data', 'Unstructured data in the form of text, often used in natural language processing.', '{"type": "object", "properties": {"text": {"type": "string"}}}', '{"example": "{"text": "Sample text data."}"}', 'PostgreSQL, MongoDB'),
('Time Series Data', 'Data points indexed in time order, typically used in statistical analysis.', '{"type": "object", "properties": {"time": {"type": "string", "format": "date-time"}, "value": {"type": "number"}}}', '{"example": "{"time": "2024-01-01T00:00:00Z", "value": 123}"}', 'InfluxDB, TimescaleDB'),
('Geospatial Data', 'Data that represents the physical location of features on Earth.', '{"type": "object", "properties": {"location": {"type": "object", "properties": {"latitude": {"type": "number"}, "longitude": {"type": "number"}}}}}', '{"example": "{"location": {"latitude": 40.7128, "longitude": -74.0060}}"}', 'PostGIS, MongoDB'),
('User Data', 'Information about users, typically used in applications.', '{"type": "object", "properties": {"user_id": {"type": "string"}, "preferences": {"type": "object"}}}', '{"example": "{"user_id": "user123", "preferences": {"theme": "dark"}}"}', 'MySQL, PostgreSQL'),
('Sensor Data', 'Data collected from sensors, often in IoT applications.', '{"type": "object", "properties": {"sensor_id": {"type": "string"}, "measurement": {"type": "number"}}}', '{"example": "{"sensor_id": "sensor1", "measurement": 25.5}"}', 'InfluxDB, TimescaleDB');