-- File: source_metrics.sql
-- Purpose: Insert initial data into the source_metrics table
-- Author: [Your Name]
-- Date: 2024-10-26
-- Version: 1.0
-- ===============================================
-- Script to Insert Initial Data into Source Metrics Table
-- ===============================================
-- Insert initial data into the source_metrics table
-- ===============================================
-- Note:
-- Ensure the 'source_metrics' table exists in your database
-- before executing this script.
-- ===============================================