-- File: source_tags.sql
-- Purpose: Insert initial data into the source_tags table
-- Author: [Your Name]
-- Date: 2024-10-26
-- Version: 1.0
-- ===============================================
-- Script to Insert Initial Data into Source Tags Table
-- ===============================================
-- Insert initial data into the source_tags table
-- ===============================================
-- Note:
-- Ensure the 'source_tags' table exists in your database
-- before executing this script.
-- ===============================================
-- NOTES:
-- 1. The tags table allows for the categorization of sources using unique tags.
-- 2. The source_tags table serves as a junction table to create a many-to-many relationship
--    between sources and tags, enabling a source to have multiple tags and a tag to be associated with multiple sources.
-- 3. The assigned_at field allows tracking of when tags were associated with sources.