-- File: language_types.sql
-- Purpose: Insert initial data into the languages table
-- ========================================================================================================

-- Inserting initial data into the language_types table
INSERT INTO language_types (language_code, language_name)
VALUES
    ('EN', 'English'),
    ('ES', 'Spanish'),
    ('FR', 'French'),
    ('DE', 'German'),
    ('IT', 'Italian'),
    ('PT', 'Portuguese'),
    ('RU', 'Russian'),
    ('ZH', 'Chinese'),
    ('JA', 'Japanese'),
    ('AR', 'Arabic'),
    ('HI', 'Hindi'),
    ('KO', 'Korean'),
    ('NL', 'Dutch'),
    ('SV', 'Swedish'),
    ('DA', 'Danish'),
    ('NO', 'Norwegian'),
    ('FI', 'Finnish'),
    ('IS', 'Icelandic'),
    ('EL', 'Greek'),
    ('TR', 'Turkish'),
    ('TH', 'Thai'),
    ('VI', 'Vietnamese'),
    ('MS', 'Malay'),
    ('TL', 'Tagalog'),
    ('HE', 'Hebrew'),
    ('UR', 'Urdu'),
    ('BN', 'Bengali'),
    ('PA', 'Punjabi'),
    ('CS', 'Czech'),
    ('HU', 'Hungarian'),
    ('RO', 'Romanian'),
    ('SK', 'Slovak'),
    ('SL', 'Slovenian'),
    ('ET', 'Estonian'),
    ('LV', 'Latvian'),
    ('LT', 'Lithuanian'),
    ('SW', 'Swahili'),
    ('KM', 'Khmer'),
    ('MY', 'Burmese'),
    ('NE', 'Nepali'),
    ('FA', 'Persian'),
    ('XH', 'Xhosa'),
    ('ZU', 'Zulu'),
    ('GA', 'Irish'),
    ('CY', 'Welsh'),
    ('MK', 'Macedonian'),
    ('SQ', 'Albanian'),
    ('HT', 'Haitian Creole'),
    ('YO', 'Yoruba'),
    ('AM', 'Amharic');